export const ENDPOINT = "https://jaapgjygcucdwgkelhts.supabase.co/rest/v1/wines";
export const API_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphYXBnanlnY3VjZHdna2VsaHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzk5MTkzODYsImV4cCI6MTk5NTQ5NTM4Nn0.KzaBF0JExLYgh9ii9eQdXPOWN421ectPioS_2FsJLeQ";
